### ISSUE TITLE
Add and test autoscaling for edx xpro deployment

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/salt-ops#854] opened 2019-05-03 01:10 UTC
In order to accomodate an unknown volume of traffic for the xpro deployment of edX we would like to try using autoscaling.

**Comment by blarghmatey** [comment] 2019-05-11 02:37
This post covers a good amount of the detail necessary for getting autoscaling set up with Salt https://blog.renaissancedev.com/from-heroku-to-aws-with-saltstack-part-2.html

**Comment by blarghmatey** [comment] 2019-05-11 02:38
Something to consider is that with too many edX nodes it starts to exhaust the number of connections on Mongo. We may need to either tune the configuration, or add more nodes to the cluster to handle that situation.

**Comment by shaidar** [comment] 2019-07-02 14:10
While testing, ran into an issue where the instances were failing to highstate. Discovered that it was a problem caused by the `datadog-uninstall` role running by default causing the ami build to fail when running `apt-get update`. Merged a PR to remove that role by default (will be submitting upstream) and need to run another ami build however we had a development freeze last week due to soft launch, so will get back to working on it this week.

**Comment by blarghmatey** [comment] 2019-07-31 19:32
@shaidar it seems like this is complete now. Can we consider this done?

**Comment by shaidar** [comment] 2019-07-31 19:36
Yeah we can open a new issue if we run into problems, but as of right now, this should be good.

**Closed by shaidar** 2019-07-31 19:36 UTC
Labels: DevOps, Epic
