### ISSUE TITLE
automated data management in dogwood

### ISSUE THREAD

**Issue by pdpinch** [mitodl/salt-ops#97] opened 2016-07-22 12:54 UTC

**Comment by pdpinch** [comment] 2016-07-22 12:54
@blarghmatey can you that this means?

**Comment by blarghmatey** [comment] 2016-07-22 13:03
This means setting up a way for snapshotting and loading data from a target source environment into the intended destination environment, both for testing and for DR purposes.

**Comment by shaidar** [comment] 2017-01-23 18:37
Duplicate of Issue#187

**Closed by shaidar** 2017-01-23 18:37 UTC
Labels: DevOps
